debug: False
max_num: -1

min_object_height: 0.02  # unit: m. Raw files with objects shorter than this world-z height are skipped; set <=0 to disable.

# for batch conversion (48GB GPU Memory)
learning_batch_size: 1024
max_cuda_workers: 32

data_name: BODex
data_path: /mnt/disk1/jiayichen/data/cuDex/sim_shadow/fc/version0828/graspdata
